### ISSUE TITLE
[question] roadmap

### ISSUE THREAD

**Issue by michael8090** [mikialex/rendiation#48]
Is there a roadmap or a plan for the project?

**Comment by mikialex** [comment]
## Flags in 2021!

### math lib related improvements

Encoding space, space conversion, matrix major, normalization(has implemented) in type system. Encoding coordinate system info like, chirality，up direction.. in type system 

Apply encoded information in down stream crate like math entity..  Apply encoded information in RAL trait, specify each platform's different coordinate system info by associate type

enrich implementation everywhere

improve test coverage, bench coverage, doc coverage

Play SIMD

### RAL related improvements

**Integrate Naga and RustGPU as shading abstraction layer, very important**

Use Glow instead of wasm webgl to support opengl natively

Make RAL more resource oriented, not like extremely matured project like gfx-rs

Try support CPU Backend?

Abstractions over ray tracing?


### Libraries, learning purpose

Retry implementing editable mesh data structure like half edge.. in rivermesh

Implement some other space partition algorithms like BSP R-tree Kd-tree.. in space indexer


### Applications, learning purpose

In rainray, Try impl metropolis light transport, multi importance sampling, enrich bxdfs, read and refactor pbrt into better abstraction. Try use RRF's scenegraph in rainray, not build another one.

Polish the RRF arch by continue developing in rinecraft.

Explore new possibility in nyxt viewer..

### Some new topic

Physics engine?  Lisp based graphics creative coding?
